- src/components/About.jsx
- src/components/ContactUs.jsx
- src/components/Footer.jsx
> component created

- src/components/Home.jsx
> navabar added in home

- src/components/Feature.jsx
- src/components/Home.jsx
feature heading style completed
> feature heading style completed

- src/components/Home.jsx
> home responsive

- src/components/Home.jsx
> home section alignment

- src/Contents.js
- src/components/Feature.jsx
- src/components/ServiceList.jsx
- src/components/Services.jsx
serviceList component created, service component compleated
> serviceList component created, service component compleated

- package-lock.json
- src/components/Home.jsx
> home section clearence

- index.css
- src/App.jsx
- src/Contents.js
- src/components/Feature.jsx
feature component responsive compleated
> feature component responsive compleated

- src/components/ServiceList.jsx
- src/components/Services.jsx
service component responsive compleated
> service component responsive compleated

- src/components/Seo.jsx
seo componet creeated succefully, responsive compleated
> seo componet creeated succefully, responsive compleated

- package-lock.json
- src/App.jsx
- src/Contents.js
- src/components/Projects.jsx
- src/components/Says.jsx
- src/components/Who.jsx
> small errors fixed

- package-lock.json
- package.json
- src/components/Projects.jsx
- src/components/Says.jsx
- src/components/Seo.jsx
says commet div design compleated
> says commet div design compleated 

- src/components/Says.jsx
small changes in says comment div
> small changes in says comment div

- src/components/Seo.jsx
> seo component design updated

- package-lock.json
- package.json
- src/components/ServiceList.jsx
- src/components/Services.jsx
animation added service component and added new library
> animation added service component

- src/components/ServiceList.jsx
>  animation added mobile view

- client/src/App.jsx
- client/src/components/About.jsx
- client/src/components/Call.jsx
- client/src/components/Home.jsx
smooth movements in each components
> smooth movements in each components

- package-lock.json
- package.json
new animations added in feature component 2
> new animations added in feature component 2

- client/src/components/Feature.jsx
- client/src/components/Seo.jsx
- client/src/components/ServiceList.jsx
- client/src/components/Services.jsx
new animation adde to featue,seo,servicelist,service components
> new animation adde to featue,seo,servicelist,service components

- client/src/Contents.js
- client/src/assets/animations/ScrollFloat.jsx
- client/src/components/AppleCardDemo.jsx
- client/src/components/Brand.jsx
- client/src/components/Call.jsx
- client/src/components/Fact.jsx
- client/src/components/Feature.jsx
- client/src/components/Seo.jsx
- client/src/components/Services.jsx
- client/src/components/Who.jsx
background heading style changed in all components
> background heading style changed in all components

- client/index.html
- client/src/components/AppleCardDemo.jsx
- client/src/components/Feature.jsx
- client/src/components/Home.jsx
- client/src/components/InfiniteMovingCardsDemo.jsx
- client/src/components/Seo.jsx
fixed mobile view align problems
> fixed mobile view align problems

- client/src/components/Fact.jsx
- client/src/components/Feature.jsx
- client/src/components/InfiniteMovingCardsDemo.jsx
- client/src/components/Seo.jsx
- client/src/components/Who.jsx
component heading responsive again updated
> component heading responsive again updated

- client/src/components/Call.jsx
> mail section

- client/src/components/Home.jsx
> home hight updated

- client/src/components/Feature.jsx
- client/src/components/Home.jsx
> again home hight updated

- client/src/components/Home.jsx
home component homeBg image height updated
> home component homeBg image height updated

- client/src/components/Feature.jsx
- client/src/components/Home.jsx
- client/src/components/Seo.jsx
- client/src/components/Who.jsx
> home vector image updated

- client/src/components/Feature.jsx
- client/src/components/ServiceList.jsx
- client/src/components/Who.jsx
> who and serviceList updated
